-- Migration: Fix All Missing Columns and Tables for Tilawah & Student Profiles
-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Add missing columns to students table
DO $$ 
BEGIN 
    -- total_tilawah_hal (The main cause of the 400 error)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='total_tilawah_hal') THEN
        ALTER TABLE students ADD COLUMN total_tilawah_hal INTEGER DEFAULT 0;
    END IF;

    -- total_hafalan
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='total_hafalan') THEN
        ALTER TABLE students ADD COLUMN total_hafalan NUMERIC DEFAULT 0;
    END IF;

    -- tempat_lahir
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='tempat_lahir') THEN
        ALTER TABLE students ADD COLUMN tempat_lahir TEXT;
    END IF;

    -- tanggal_lahir
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='tanggal_lahir') THEN
        ALTER TABLE students ADD COLUMN tanggal_lahir TEXT;
    END IF;

    -- jenis_kelamin
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='jenis_kelamin') THEN
        ALTER TABLE students ADD COLUMN jenis_kelamin TEXT;
    END IF;

    -- alamat
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='alamat') THEN
        ALTER TABLE students ADD COLUMN alamat TEXT;
    END IF;

    -- hp
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='hp') THEN
        ALTER TABLE students ADD COLUMN hp TEXT;
    END IF;

    -- nama_ayah
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='nama_ayah') THEN
        ALTER TABLE students ADD COLUMN nama_ayah TEXT;
    END IF;

    -- nama_ibu
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='nama_ibu') THEN
        ALTER TABLE students ADD COLUMN nama_ibu TEXT;
    END IF;

    -- sekolah_asal
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='sekolah_asal') THEN
        ALTER TABLE students ADD COLUMN sekolah_asal TEXT;
    END IF;
END $$;

-- 2. Create Tilawah table if not exists
CREATE TABLE IF NOT EXISTS tilawah (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    entries JSONB DEFAULT '{}'::jsonb,
    summary JSONB DEFAULT '{}'::jsonb,
    approval JSONB DEFAULT '{"ortu": {"status": false}, "guru": {"status": false}}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(student_id, date)
);

-- 3. Enable RLS for tilawah
ALTER TABLE tilawah ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for tilawah
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'tilawah' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON tilawah FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'tilawah' AND policyname = 'Enable insert for authenticated users') THEN
        CREATE POLICY "Enable insert for authenticated users" ON tilawah FOR INSERT WITH CHECK (auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'tilawah' AND policyname = 'Enable update for authenticated users') THEN
        CREATE POLICY "Enable update for authenticated users" ON tilawah FOR UPDATE USING (auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'tilawah' AND policyname = 'Enable delete for authenticated users') THEN
        CREATE POLICY "Enable delete for authenticated users" ON tilawah FOR DELETE USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- 5. Create Indexes for tilawah
CREATE INDEX IF NOT EXISTS idx_tilawah_student_id ON tilawah(student_id);
CREATE INDEX IF NOT EXISTS idx_tilawah_date ON tilawah(date);
