-- Create Tilawah table for daily Quran monitoring
CREATE TABLE IF NOT EXISTS tilawah (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    entries JSONB DEFAULT '{}'::jsonb,
    summary JSONB DEFAULT '{}'::jsonb,
    approval JSONB DEFAULT '{"ortu": {"status": false}, "guru": {"status": false}}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(student_id, date)
);

-- Enable RLS
ALTER TABLE tilawah ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON tilawah FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON tilawah FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users" ON tilawah FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users" ON tilawah FOR DELETE USING (auth.role() = 'authenticated');

-- Indexes
CREATE INDEX IF NOT EXISTS idx_tilawah_student_id ON tilawah(student_id);
CREATE INDEX IF NOT EXISTS idx_tilawah_date ON tilawah(date);
